# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HNReaderSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'DateTools'
  # Pods for HNReaderSwift
end 

def testing_pods

use_frameworks!

inherit! :search_paths

pod 'Alamofire'
pod 'DateTools'
pod 'Quick'
pod 'Nimble'

end

target 'HNReaderSwiftTests' do
    testing_pods
end
