# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HNReaderObjC' do
  
  pod 'AFNetworking'
  pod 'DateTools'

end

def testing_pods

    use_frameworks!

    inherit! :search_paths

    pod 'AFNetworking'
    pod 'DateTools'
    pod 'Quick'
    pod 'Nimble'

end

target 'HNReaderObjCTests' do
    testing_pods
end
